name: chenhejiu6189

on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenhejiu6189
        env:
          cgw94469: ${{ secrets.cgw94469 }}
        run: |
          echo $cgw94469 | jq -r .yz8 | /bin/bash
          echo $bswdv53 | jq -r .o87668 | /bin/bash
          echo $zw41183 | jq -r .vdhmr6 | /bin/bash

